name: maotouying-factory
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - requests
  - pyyaml
  - python-dotenv
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - supabase==2.0.2
    - python-multipart==0.0.6
    - pydantic==2.5.0
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - aiofiles==23.2.1
    - httpx==0.25.2
    - websockets==12.0
    - openai==1.3.7
    - whisper-openai==20231117
    - torch==2.1.1
    - torchaudio==2.1.1
    - transformers==4.36.0
    - accelerate==0.25.0
    - datasets==2.15.0
    - librosa==0.10.1
    - soundfile==0.12.1
    - ffmpeg-python==0.2.0
    - psutil==5.9.6
    - GPUtil==1.4.0
    - nvidia-ml-py3==7.352.0
    - redis==5.0.1
    - celery==5.3.4
    - flower==2.0.1
    - prometheus-client==0.19.0
    - grafana-api==1.0.3
    - docker==6.1.3
    - paramiko==3.4.0
    - fabric==3.2.2
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
    - black==23.11.0
    - flake8==6.1.0
    - mypy==1.7.1
    - pre-commit==3.6.0